version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 8G
        reservations:
          cpus: "1"
          memory: 1G
###############################################
  servicea:
    image: vahidmostofi/micromuck-nodejs:v1
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 10080:10080
    depends_on: 
      - jaeger
    environment:
      - SERVICE_NAME=servicea
      - WORKER_COUNT=1
      - SEED=9
      - PORT=10080
      - MEAN_RESPONSE_TIMES={"req1":-1, "req2":-1, "req3":-1, "req4":-1, "req5":-1}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 3G
        reservations:
          cpus: "1"
          memory: 0.7G
###############################################
  serviceb:
    image: vahidmostofi/micromuck-nodejs:v1
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 10081:10081
    depends_on: 
      - jaeger
    environment:
      - SERVICE_NAME=serviceb
      - WORKER_COUNT=1
      - SEED=9
      - PORT=10081
      - MEAN_RESPONSE_TIMES={"req1":15, "req2":5, "req3":21, "req4":4, "req5":80}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 3G
        reservations:
          cpus: "1"
          memory: 0.7G
###############################################
  servicec:
    image: vahidmostofi/micromuck-nodejs:v1
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 10082:10082
    depends_on: 
      - jaeger
    environment:
      - SERVICE_NAME=servicec
      - WORKER_COUNT=1
      - SEED=9
      - PORT=10082
      - MEAN_RESPONSE_TIMES={"req1":8, "req2":6, "req3":18, "req4":10, "req5":83}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 3G
        reservations:
          cpus: "1"
          memory: 0.7G
###############################################
  serviced:
    image: vahidmostofi/micromuck-nodejs:v1
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 10083:10083
    depends_on: 
      - jaeger
    environment:
      - SERVICE_NAME=serviced
      - WORKER_COUNT=1
      - SEED=9
      - PORT=10083
      - MEAN_RESPONSE_TIMES={"req1":7,"req2":17,"req3":25,"req4":14,"req5":86}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 3G
        reservations:
          cpus: "1"
          memory: 0.7G
###############################################
  servicee:
    image: vahidmostofi/micromuck-nodejs:v1
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 10084:10084
    depends_on: 
      - jaeger
    environment:
      - SERVICE_NAME=servicee
      - WORKER_COUNT=1
      - SEED=9
      - PORT=10084
      - MEAN_RESPONSE_TIMES={"req1":10,"req2":20,"req3":15,"req4":26,"req5":10}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 3G
        reservations:
          cpus: "1"
          memory: 0.7G
###############################################
  servicef:
    image: vahidmostofi/micromuck-nodejs:v1
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 10085:10085
    depends_on: 
      - jaeger
    environment:
      - SERVICE_NAME=servicef
      - WORKER_COUNT=1
      - SEED=9
      - PORT=10085
      - MEAN_RESPONSE_TIMES={"req1":5,"req2":5,"req3":7,"req4":4,"req5":7}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 3G
        reservations:
          cpus: "1"
          memory: 0.7G
###############################################
  serviceg:
    image: vahidmostofi/micromuck-nodejs:v1
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 10086:10086
    depends_on: 
      - jaeger
    environment:
      - SERVICE_NAME=serviceg
      - WORKER_COUNT=1
      - SEED=9
      - PORT=10086
      - MEAN_RESPONSE_TIMES={"req1":17,"req2":12,"req3":12,"req4":23,"req5":108}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 3G
        reservations:
          cpus: "1"
          memory: 0.7G
###############################################
  serviceh:
    image: vahidmostofi/micromuck-nodejs:v1
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 10087:10087
    depends_on: 
      - jaeger
    environment:
      - SERVICE_NAME=serviceh
      - WORKER_COUNT=1
      - SEED=9
      - PORT=10087
      - MEAN_RESPONSE_TIMES={"req1":17,"req2":12,"req3":5,"req4":12,"req5":18}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 3G
        reservations:
          cpus: "1"
          memory: 0.7G
###############################################
  servicei:
    image: vahidmostofi/micromuck-nodejs:v1
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 10088:10088
    depends_on: 
      - jaeger
    environment:
      - SERVICE_NAME=servicei
      - WORKER_COUNT=1
      - SEED=9
      - PORT=10088
      - MEAN_RESPONSE_TIMES={"req1":13,"req2":19,"req3":12,"req4":12,"req5":15}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 3G
        reservations:
          cpus: "1"
          memory: 0.7G
###############################################
  servicej:
    image: vahidmostofi/micromuck-nodejs:v1
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 10089:10089
    depends_on: 
      - jaeger
    environment:
      - SERVICE_NAME=servicej
      - WORKER_COUNT=1
      - SEED=9
      - PORT=10089
      - MEAN_RESPONSE_TIMES={"req1":13,"req2":19,"req3":12,"req4":25,"req5":30}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 3G
        reservations:
          cpus: "1"
          memory: 0.7G